### PR TITLE
Add cobertura.xml files for codecov

### PR DESCRIPTION
**Pull request by jamesray1**
As per https://github.com/Drops-of-Diamond/diamond_drops/issues/11.

### CODE REVIEW

**Comment by samparsky** [comment]
@jamesray1 I don't think this PR fixes the build issue, you can check out the job on Travis [(here)](https://travis-ci.org/Drops-of-Diamond/diamond_drops/jobs/382446340) 
I don't think we need to add these files to the repository. The files you added are automatically generated by Travis CI when the code is being built.
The changes we need to make is to fix the failing build is in the Travis CI yml file.
```sh
  for file in target/debug/examplerust-*[^\.d]; do mkdir -p "target/cov/$(basename $file)"; ./kcov-build/usr/local/bin/kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done &&

```
The error is in
`
target/debug/examplerust-*[^\.d]; 
`

It should be diamond-drops-node I think instead of examplerust. 
I feel it should be 
`
target/debug/build/diamond-drops-node-*[^\.d]; 

`

**Comment by jamesray1** [comment]
Ah yes, looks like you're right! The line should be used for each crate, i.e.:

`for file in *[_A-Za-z0-9]/target/debug/diamond_drops*[_A-Za-z0-9]-*[^\.d]; do mkdir -p "target/cov/$(basename $file)"; ./kcov-build/usr/local/bin/kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done &&`

**Comment by samparsky** [comment]
@jamesray1 You still need to remove the 271 files added.

**Comment by jamesray1** [comment]
Yep, I'm making another PR.

**Comment by jamesray1** [comment]
What shall I use for your email address in the co-author field? You may want to use a no-reply one to prevent spam.

**Comment by jamesray1** [comment]
To find your GitHub-provided no-reply email, navigate to your email settings page under "Keep my email address private."

    To find the email you used to configure Git on your computer, run git config user.email on the command line.

https://help.github.com/articles/creating-a-commit-with-multiple-authors/

**Comment by samparsky** [comment]
@jamesray1 diamond_drops is setup as a library not an executable binary, the current kcov structure assumes it an executable which is leading to failing build.

The email is 8148384+samparsky@users.noreply.github.com

**Comment by jamesray1** [comment]
Rebased to #80, however that didn't fix the issue. @samparsky, feel free to take the initiative on this.

**Pull request closed without merging**
