### PR TITLE
Fix errors in src/lib.rs

### PR DESCRIPTION
**Pull request by jamesray1**

### CODE REVIEW

**Comment by jamesray1** [comment]
When I run cargo make test-all on these changes I get the error:
```
error: Could not compile `tiny-keccak`.

Caused by:
  process didn't exit successfully: `rustc --crate-name tiny_keccak /home/james/.cargo/registry/src/github.com-1ecc6299db9ec823/tiny-keccak-1.4.1/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=b5e8e3638fbc1be2 -C extra-filename=-b5e8e3638fbc1be2 --out-dir /home/james/dod/target/debug/deps -L dependency=/home/james/dod/target/debug/deps --extern crunchy=/home/james/dod/target/debug/deps/libcrunchy-88d10eef0a5335a1.rlib --cap-lints allow` (signal: 9, SIGKILL: kill)
```

**Comment by jamesray1** [comment]
To reproduce:

Clone https://github.com/jamesray1/diamond_drops

and checkout to fix-errors-in-lib-rs

then run `cargo make test-all`.

**Comment by jamesray1** [comment]
https://github.com/debris/tiny-keccak/issues/33

**Comment by timxor** [comment]
Oh interesting, haha looks like you went down the rabbit hole on this one ehh. Get it fixed?

**Comment by timxor** [comment]
Oh yeah I see, got it merged and a version bump fixed it. Nice!

**Pull request merged**
