### PR TITLE
feat: Thread names with enum. Fix warnings. Handle thread panic 

### PR DESCRIPTION
**Pull request by ltfschoen**

### CODE REVIEW

**Comment by ChosunOne** [comment]
Good call on adding names to the threads!  I think this should be good to merge.

**Comment by ltfschoen** [comment]
@ChosunOne @jamesray1 I've added additional commits

**Comment by ltfschoen** [comment]
@ChosunOne it looks like the latest branch is now 'collator' rather than 'basic_cli'. should i be making a pull request into that branch instead? are you happy with my latest changes?

**Comment by ltfschoen** [comment]
I'm going to create a separate PR into 'collator'

**Pull request closed without merging**
